baseURL = 'https://addisonwen.com/'
languageCode = 'en-us'
title = 'Addison Wen'

theme = 'shibui'

[params.author]
  name = "Addison Wen"
  email = "info@addisonwen.com"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = true
    tabWidth = 4
    style = "algol_nu"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']